### ISSUE TITLE
R4i Max (www.r4imax.com) Support

### ISSUE THREAD

**Issue by IvanMolina99** [kitling/flashcart_core#16] opened 2017-08-18 00:14 UTC
Hi! This is the R4i Max flashcart info

**1-Game Header:** 

> Touch! Bomberman Land
> Nintendo

![fre3](https://user-images.githubusercontent.com/17816606/29438720-e1aff698-83b8-11e7-83bf-570279453f9c.png)

**2-Flashcart skin**
![r43](https://user-images.githubusercontent.com/17816606/29438739-005c2de6-83b9-11e7-9638-e588eee8c7e7.jpg)

**3-Flashcart Board**

![f4er 1](https://user-images.githubusercontent.com/17816606/29439439-e32fe55a-83bd-11e7-957b-715325c451a5.jpeg)
![f4er 2](https://user-images.githubusercontent.com/17816606/29439440-e3319bde-83bd-11e7-869b-07172a664288.jpeg)
![img-20170818-wa0026](https://user-images.githubusercontent.com/17816606/29461963-edc1fd26-842d-11e7-95e3-8d780775d286.jpg)

> PD:Sorry by the bad image quality :(

**4-Flashcart Kernel files**
![gt5](https://user-images.githubusercontent.com/17816606/29438877-eb2c46c6-83b9-11e7-8797-2dcc7a3a3f80.png)
Kernel download link: http://www.r4imax.com/download/R4i%20V4.5%20English.zip

**5-Update files:**

> [Update for nintendo dsi y dsi xl 1.4.4 y 3ds 4.4.0-10](http://www.r4imax.com/download/up3dsv44.zip)

> [Update for nintendo 3DS with 7.1.0-14 version (only for new r4i models)](http://www.r4imax.com/download/up3dsv62.zip)

**6-Flashcart dump:**

> ChipID:  000007C2
> HW Rev: FFFFFFFF

**7-R4i Max website:** 

> http://r4imax.com/index.php

If you need more details tell me :)

**Comment by Parker11011** [comment] 2017-08-18 00:21
Looks similar to R4isdhc :( without updating archives 

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kitling** [comment] 2017-08-18 02:09
Can you find a firmware/BIOS/(whatever they call it) updater? This is more useful to us than the kernel.

**Comment by d3m3vilurr** [comment] 2017-08-18 03:51
@kitling 

* Update for nintendo dsi y dsi xl 1.4.4 y 3ds 4.4.0-10 [updater1][]
* Update for nintendo 3DS with 7.1.0-14 version (only for new r4i models) [updater2][]
are looks updater.

[updater1]: http://www.r4imax.com/download/up3dsv44.zip
[updater2]: http://www.r4imax.com/download/up3dsv62.zip

**Comment by IvanMolina99** [comment] 2017-08-18 06:36
@d3m3vilurr Thanks! :) I updated the post with this information

**Comment by DiamondMinerITA** [comment] 2017-08-18 12:00
Wow. It's basically my card. It's like the dualcore from r4isdhc.com.
The pcb is the only difference.
It has got only like some resistor missing.
This may work with the r4isdhc.com dualcore.

**Comment by dark-samus** [comment] 2017-08-18 15:12
yeah, this looks similar to the other cards, the only difference I see at a quick glance is some slight PCB changes.... I'll maybe take a look at the updater later.

**Comment by IvanMolina99** [comment] 2017-08-18 15:52
@dark-samus Thanks! :)

**Comment by deadair3210** [comment] 2017-08-19 21:11
I belive the R4.dat is the update file, the flashcart menu has an option to look on the sd card for a update

**Comment by IvanMolina99** [comment] 2017-08-19 21:50
@deadair3210 
The update files are these:
Update for nintendo dsi y dsi xl 1.4.4 y 3ds 4.4.0-10
http://www.r4imax.com/download/up3dsv44.zip

Update for nintendo 3DS with 7.1.0-14 version (only for new r4i models)
http://www.r4imax.com/download/up3dsv62.zip

You only have to put  the update.nds file on the root of your SD and run it directly in your flashcart like a normal .nds file and the flashcart will be update to the latest version

**Comment by Juanito9001** [comment] 2017-08-20 00:48
@kitling in the issue R4i sdhc rts silver, there's a firmware updater ( old ver) of that model

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DiamondMinerITA** [comment] 2017-08-20 11:17
Any news?

**Comment by IvanMolina99** [comment] 2017-08-20 11:32
@DiamondMinerITA 
I don't know...
We should be patient, they probably have a lot of work

**Comment by hedgeberg** [comment] 2017-08-22 00:14
We have a lot of work to do. These cards are at the bottom of the queue, and none of us have them. We are currently working on R4i SDHC and SCDS2/2p. Unless one of you wants to do the reverse engineering this won't get supported until we both get one of these cards and finish the cards were working on. When there's news we'll say so.

**Comment by IvanMolina99** [comment] 2017-08-22 00:56
@hedgeberg 
Yeah! I know that these cards aren't a priority...
I recently bought an Acekard 2i HW-81 and a R4i Gold 3DS RTS by the Ntrboothax compatibility.

I only opened an issue of this card by the fact if this card could had support some day.

Don't worry and good luck working with the others flashcart :)

**Comment by dark-samus** [comment] 2017-08-24 23:44
I'm closing this issue due to this being a duplicate of another card. Please post all future posts about this card to #11 please. Thanks :)

**Closed by dark-samus** 2017-08-24 23:44 UTC

**Comment by byggames** [comment] 2022-02-05 16:48
Hi, How can I run my DS games on the 3DS with this type of card?

**Comment by kitlith** [comment] 2022-02-06 02:15
@byggames that is off-topic for this project.

**Comment by byggames** [comment] 2022-02-06 08:42
> @byggames that is off-topic for this project.

Oh, sorry
