### ISSUE TITLE
R4Infinity Dual Core 2016 (R4Infinity.com)

### ISSUE THREAD

**Issue by supertacomx** [kitling/flashcart_core#59] opened 2017-09-09 03:51 UTC
This is another version for the R4Infinity. I've already tried the updated files to dump the cartridge, but say's it's not recognized. It says 2016 and Dual Core.

The website is the same as the title, the firmware updater is supposedly
(http://www.r4infinity.com/download/fwupdate2_for_3dsV7.0.rar)
I haven't tried it yet. I'm scared haha.

I hope the post is ok.

I'll post the pictures.

ChipID: 00000FC2
HW Revision: 2A2A2A2A

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

![20170908_212555](https://user-images.githubusercontent.com/31786770/30236752-58c1ebc0-94de-11e7-9dc6-83f9ef3eb09a.jpg)
![20170908_212156](https://user-images.githubusercontent.com/31786770/30236753-689e6320-94de-11e7-8de8-f65eace3d5d1.jpg)
![20170908_212115](https://user-images.githubusercontent.com/31786770/30236755-77097b2a-94de-11e7-99d1-3a7e326142f4.jpg)
![20170908_212102](https://user-images.githubusercontent.com/31786770/30236757-855ee21e-94de-11e7-98b6-f10fd39d8131.jpg)

</p></details> 

GM9 Untrimmed Dump: 
[SPONGEBOB_AP_AL3P78_00.zip](https://github.com/kitling/flashcart_core/files/1289520/SPONGEBOB_AP_AL3P78_00.zip)

**Comment by dark-samus** [comment] 2017-09-10 20:23
duplicate of #3

**Closed by dark-samus** 2017-09-10 20:23 UTC
