### ISSUE TITLE
R4i 3DS (4.5)

### ISSUE THREAD

**Issue by HackerBoy0412** [kitling/flashcart_core#19] opened 2017-08-21 23:30 UTC
Will that Cart ever Work?
ChipID: 000007C2
HW Rev: FFFFFFFF

![20170822_012643](https://user-images.githubusercontent.com/27073934/29542198-b1227cf2-86d9-11e7-859a-1c82f2a1f462.jpg)
![20170822_012652](https://user-images.githubusercontent.com/27073934/29542225-dc6456f6-86d9-11e7-91e8-f23b9753a30b.jpg)
![20170822_012746](https://user-images.githubusercontent.com/27073934/29542242-ffc3f958-86d9-11e7-8540-a8f7c64fbd63.jpg)
![20170822_012809](https://user-images.githubusercontent.com/27073934/29542273-24f093b2-86da-11e7-87df-04fb4695ba4d.jpg)

**Comment by Juanito9001** [comment] 2017-08-21 23:33
This ChipID and HWrev was posted before in other issue, btw, the same as mine

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kitling** [comment] 2017-08-22 00:16
Closing as duplicate of #14, which already has more information.

If this is actually a different cart, feel free to let us know and we can reopen this issue.

**Closed by kitling** 2017-08-22 00:16 UTC
