### ISSUE TITLE
TTDS Clones (various)

### ISSUE THREAD

**Issue by mlinares1998** [kitling/flashcart_core#8] opened 2017-08-14 00:22 UTC
Did Ace3DS (1st-gen/Non-Plus) Flashcard would be supported?
The Flashcard itself is another TTDS based card with upgradeable firmware. Boots the Kernel from 3DSCARD.dat file. Works well with Retrogamefan TTDS YSMenu kernel.
The Team stopped upgrading the card after 3DS FW 4.3.0-10, afterwards deleted any reference of it on their site in favor of "Plus" model. 
The latest firmware it has supports 4.3.0-10 but all the links on net are dead, the most updated firmware i was able to found was 4.0.0-7 support update from Filetrip: 
https://filetrip.net/nds-downloads/flashcart-files/download-ace3ds-update-3ds-v4-0-0-7-package-4-0-0-7-f28254.html
The update package has 2 files, the nds updater and a 4MB sized "update.dat" file which i suppouse is the Firmware itself.
NTRBoot Flasher gives me the following data (my card has 4.3.0-10 FW):
ChipID: 00000FC2
HW Rev: 00000000
There are some pics of the PCB, sorry for the low quality i don't have any better camera here xP:
![img_20170814_001336](https://user-images.githubusercontent.com/15200008/29254517-987e4774-8064-11e7-93f3-d3849105eb53.jpg)
![img_20170814_001343](https://user-images.githubusercontent.com/15200008/29254518-987fc7ac-8064-11e7-8649-d2321691b606.jpg)
![img_20170814_001420](https://user-images.githubusercontent.com/15200008/29254519-9882d794-8064-11e7-9036-00c043549014.jpg)
![img_20170814_001505](https://user-images.githubusercontent.com/15200008/29254521-98888784-8064-11e7-8431-fd8a1cf3ee5b.jpg)
![img_20170814_001243](https://user-images.githubusercontent.com/15200008/29254520-9888819e-8064-11e7-94a7-4b4151b8149f.jpg)

Hope all this info helps, thanks :D

**Comment by hectortillo** [comment] 2017-08-14 15:42
I have another card that gives me the same chip id. And the same HW revision (all 0's xD) but mine isnt Ace 3ds.  Mine is a r4 revolution. I think if it could be supported as well.  Does it could be possible?

**Comment by dark-samus** [comment] 2017-08-14 16:25
@mlinares1998 added to the todo list.

**Comment by EinyWf** [comment] 2017-08-15 07:41
Here's all the info I posted in another issue, but it seems it's another TTDS clone.
ChipID: 00000FC2
HW Rev: 00000000
Photos:
![img_20170814_213602](https://user-images.githubusercontent.com/31015886/29288759-3ff710e6-813a-11e7-8ae4-e4607e04dda2.jpg)
![img_20170814_213619](https://user-images.githubusercontent.com/31015886/29288768-4b6d138a-813a-11e7-9f5e-86dbd19ddbef.jpg)
![img_20170814_213434](https://user-images.githubusercontent.com/31015886/29288783-5cf79030-813a-11e7-82f3-0732d66529e7.jpg)
![img_20170814_213451](https://user-images.githubusercontent.com/31015886/29288790-61eb7278-813a-11e7-86b2-60aa26218c8d.jpg)

Dump made with this test build [ntrboot_flasher.zip](https://github.com/kitling/flashcart_core/files/1222726/ntrboot_flasher.zip):
[backup.zip](https://github.com/kitling/flashcart_core/files/1223133/backup.zip)

**Comment by Craftyawesome** [comment] 2017-08-16 01:42
Both my plus's have the same chip id and hw rev. Here is a backup of the older one created with the above build
[backup.zip](https://github.com/kitling/flashcart_core/files/1226834/backup.zip)

**Comment by mlinares1998** [comment] 2017-08-16 03:08
@EinyWf Apparently my Ace3DS and your R4i are based on the same PCB design. The FW updater file structure matchs Ace3DS one too, but i used an Hex comparison tool and the dumps differ completely xD. 
@Craftyawesome Your dump seems invalid xP, i opened it on HxD and is just empty "00's".
![image](https://user-images.githubusercontent.com/15200008/29345503-3a43fcd0-820d-11e7-8ebe-f0003e1d5d3e.png)
There is my card FW dump taken with the test build linked above, the program identifies the card as R4 SDHC Dual Core.
[backup.zip](https://github.com/kitling/flashcart_core/files/1226931/backup.zip)

**Comment by dark-samus** [comment] 2017-08-16 03:29
yeah, that build really shouldn't be used by people, but ofc it's being circulated around. This cart seems to be a clone of a DSTT, which in turn is supposedly a clone of a supercard ds one. (yay! /s)

**Comment by EinyWf** [comment] 2017-08-16 07:59
@mlinares1998 Well, I'm not really sure what firmware I have in the flashcart (it's not the "official" one from www.r4i-gold.hk I linked earlier) I think it's from www.r4i-gold.cc (not r4igold.cc) because it loads the kernel from R4i.3ds file. The original firmware loads the kernel from 3DSCARD.dat as the Ace3DS.

@dark-samus I know that build shouldn't be used by people, I used it when I thought my cart was a different clone (the one in the issue where that build was fisrt linked), just linked it here for reference as I already had that - probably useless - dump.

**Comment by mlinares1998** [comment] 2017-08-16 17:00
@EinyWf That would explain why dumps differ that much xD, maybe the r4i-gold.cc team FW is different from Ace3DS/r4i-gold.hk one  but at the end seems designed for the same PCB. 
Fun Fact, r4i-gold.cc site is pretty dead right now xD.
![image](https://user-images.githubusercontent.com/15200008/29374661-3041971a-8280-11e7-9645-77553cc83900.png)

@dark-samus
Thanks for all your support :D
I always thought TTDS cart was in fact a Legit product, never suspected of it being just another clone. 
Definitely the clones story won't ever ends xD.

BTW is there any risk involved on using the test build to take FW dumps? just for curiosity sake xD.

**Comment by EinyWf** [comment] 2017-08-16 19:10
@mlinares1998 
I can see some similarities between our dumps, the data it's almost completely different but you can see similar "sections" also there's some patterns, e.g. there's sections in your dump completely filled with FF and the same sections in mine seems to have data, but actually have the same sequence (garbage probably) repeated over and over. The big section witch clear text in my dump have some data at the beginning in yours (compressed maybe?) and the rest is filled with FF. Anyway you've probably seen the problem with our dumps. It's just the same 16k repeated 128 times.

**Comment by Craftyawesome** [comment] 2017-08-16 21:54
Actually I can't seem to get it to dump either of my plus's. It dumps seemingly fine other than getting to 99% instantly. Both dump 00s unless I remove sd in which case it dumps FF. A normal ds game also dumps 2 mB of FF. The DS cannot detect the cards at all without the sd.

The closest thing to an updater I found was https://filetrip.net/dl?Rqf4x1K5L5

**Comment by mlinares1998** [comment] 2017-08-16 22:15
@Craftyawesome The best thing you can do right now is open the card, take pictures of the PCB and send them, maybe the PCB is different due Ace3DS+ is a replacement of 1st gen one (TTDS based).
The link you sent isn't the Firmware of the card, it's the Kernel which in easy terms is the OS of the card which is launched from your SD, While the Firmware is the program installed on Card FLASH chip and launchs the Kernel.
Due the Kernel is Wood rather TTMenu/YSMenu based, maybe the card is based upon AK2i or another clone design, that's why the Test build fails to dump firmware, remember that the test build is a WIP and maybe your card design isn't supported at the moment, clones sometimes can be tricky.
Fun fact the Ace3DS site is dead now xD, it was online 2 days ago.
@dark-samus Should i edit the Issue title adding Ace3DS+?

**Comment by dark-samus** [comment] 2017-08-16 23:34
OK, someone in IRC found an updater for DSTT clones. Could you guys run it and see what it says (no need to actually flash the cart though!) 

https://usercontent.irccloud-cdn.com/file/dGlc45VI/DSTT_FakeRecovery_v1.17.zip

it seems to support clones that use a bunch of different flash chips, so this could be really good for us.

**Comment by mlinares1998** [comment] 2017-08-16 23:38
@dark-samus You mean run the updater and post output Without flashing right?
I just hope it doesn't auto-start the upgrade xD
Gimme a moment.

**Comment by dark-samus** [comment] 2017-08-16 23:39
@mlinares1998 I've checked, it has "wait for user input before flashing" code, so don't worry. Also make sure to read my edited comment. :)

**Comment by dark-samus** [comment] 2017-08-16 23:42
also, just in case you were curious:

**Comment by Craftyawesome** [comment] 2017-08-16 23:45
On older versions of the website there is a ace3ds fix all file. It was ftp but I found it on my sd.
[ace3ds_fix_all.zip](https://github.com/kitling/flashcart_core/files/1229762/ace3ds_fix_all.zip)
Don't know what it does but
old 
![img_20170816_192216](https://user-images.githubusercontent.com/19976035/29389846-ba75b0f8-82ba-11e7-8eac-60dd5c6cf0f6.jpg)
new
![img_20170816_193426](https://user-images.githubusercontent.com/19976035/29389872-ca96d2d2-82ba-11e7-9bf7-92c705c3657f.jpg)

Pics of older plus PCB
![img_20170816_193426](https://user-images.githubusercontent.com/19976035/29389937-1f456f1e-82bb-11e7-899a-dbf052d3e369.jpg)
![img_20170816_193435](https://user-images.githubusercontent.com/19976035/29389938-1f601e86-82bb-11e7-87d3-18bbb3001388.jpg)

Not sure I want to take my newer one apart but it doesn't have 002.
Also that dstt thing reader says not and in writer it seems to get stuck with the top screen white.

**Comment by mlinares1998** [comment] 2017-08-16 23:48
@dark-samus Copying the file to my MSD right now :D don't worry just wanna be the most safe i can because on my country find new flashcards is just... complex and expensive xD
I'll tell you if my Flash Chip is supported i have no problems opening the card.
@Craftyawesome your PCB is different to one ones we're studying here, i really doubt your card is TTDS based.

**Comment by mlinares1998** [comment] 2017-08-16 23:51
@dark-samus which file i have to launch?

![image](https://user-images.githubusercontent.com/15200008/29390111-4aad5436-82bc-11e7-9023-e97c0ed38951.png)

I'm currently using retrogamefan FW and my 3DS to run the updater all OK? xD

**Comment by dark-samus** [comment] 2017-08-16 23:53
yeah, that's fine. Run the "DsttFlashWriter.nds" file

**Comment by dark-samus** [comment] 2017-08-16 23:59
@Craftyawesome tbh, looks like that's an ace3ds plus, which it totally different

**Comment by mlinares1998** [comment] 2017-08-17 00:02
@dark-samus Top screen is white, bottom screen asks me to change DSTT and press A.
What i gotta do now?

**Comment by dark-samus** [comment] 2017-08-17 00:04
I think that means it didn't detect a supported DSTT...

**Comment by dark-samus** [comment] 2017-08-17 00:06
ah, seems it's telling you to put in the DSTT and press A (it hasn't looked for one yet.) Just press A then it'll check the flash type.

**Comment by mlinares1998** [comment] 2017-08-17 00:06
OK NP xD

**Comment by mlinares1998** [comment] 2017-08-17 00:07
It printed 44415449 Not Support Device xP

**Comment by dark-samus** [comment] 2017-08-17 00:08
hmm, maybe this isn't a DSTT after all..

**Comment by mlinares1998** [comment] 2017-08-17 00:10
Considering these flashcards are much newer than Original TTDSi was, it died after 3DS 2.1 FW xD, the design should be slightly different.
The original firmware was Indeed YSMenu based, same NO CARD Loading TTDS designs.

**Comment by mlinares1998** [comment] 2017-08-17 00:38
@dark-samus  This is a comparison between FW's
Up TTDS 1.17
Down Ace3DS
![image](https://user-images.githubusercontent.com/15200008/29391036-704a29a2-82c2-11e7-95e0-3e5d976f4422.png)

Kernel files folder:
![image](https://user-images.githubusercontent.com/15200008/29391072-a748258a-82c2-11e7-8722-30fcc89b3924.png)

The file structure from Ace3DS differs from TTMenu, some files seems new but others seems more a rename than anything.

![image](https://user-images.githubusercontent.com/15200008/29391119-cbe144b2-82c2-11e7-92ad-1f07f54140c2.png)

**Comment by Craftyawesome** [comment] 2017-08-17 00:41
@dark-samus I know it's a plus. It just has the same chip id so we didn't know if it was going to effectively be different.

I'm going to create a seperate request unless someone convinces me they are close enough.

**Comment by dark-samus** [comment] 2017-08-17 04:14
@Craftyawesome yeah, the ak2i, several of the r4 sdhc revs, the DSTT, and most other cards do share that card ID. It's a fairly standard one, iirc even a lot nintendo carts use that chipID

**Comment by DiamondMinerITA** [comment] 2017-08-17 16:18
hi, i've got one very similar. Isn't in the ttds kernel image but it's veery similar.
It has a similar pcb and design.
It's a r4i sdhc upgradable revolution for I XL / I LL / I / L / DS/ www.r4iasdhc.com
![card](https://user-images.githubusercontent.com/31065808/29422425-7040a3a8-8378-11e7-900a-fd365716953a.png)

**Comment by DiamondMinerITA** [comment] 2017-08-17 16:50
Do you want the kernel zip? I got 2, one english and one italian

**Comment by mlinares1998** [comment] 2017-08-17 17:09
Yeah, upload the english one :D

**Comment by DiamondMinerITA** [comment] 2017-08-17 17:10
sorry, i had only the italian. after checking the cards where others.

**Comment by DiamondMinerITA** [comment] 2017-08-17 17:12
https://mega.nz/#!t5dwCKgJ!EVz1lH5mZkKFMa-SFGbWmqcpcVgMJtHyEW8GgyH4x6g
here we go

**Comment by DiamondMinerITA** [comment] 2017-08-17 17:35
if there is something in italian i can translate it to you. I'm italian

**Comment by mlinares1998** [comment] 2017-08-17 17:38
@DiamondMinerITA 
Your Kernel seems 1:1 compared to the Ace3DS one, it's the same Card with another sticker xD.
The only diff is your card boots from iLL.iL file rather 3DSCARD.dat

Up r4aiasdhc.com
down ACE3DS

![image](https://user-images.githubusercontent.com/15200008/29425427-38d6240a-8351-11e7-8928-0c87632aabbc.png)

System Folders 
Up r4aiasdhc.com
down ACE3DS

![image](https://user-images.githubusercontent.com/15200008/29425450-4d0297f6-8351-11e7-87ac-0e247be05935.png)

**Comment by DiamondMinerITA** [comment] 2017-08-17 17:41
Lol, well, at least my card is compatible. We will need to wait.
@mlinares1998 .

**Comment by EinyWf** [comment] 2017-08-17 17:49
@dark-samus 
I have tried the updater for DSTT clones: 44495053 Not Supprt Device.

**Comment by mlinares1998** [comment] 2017-08-17 17:55
@EinyWf 
I guess the updater was designed for direct clones of original TTDS/TTDSi cards which were bricked by TTDS 1.17 Kernel (as states included Readme). Our cards by other hand seems based on TTDS but with a slightly different design. I guess the best thing we can do right now is wait until devs RE the cards Firmware...

**Comment by DiamondMinerITA** [comment] 2017-08-17 22:37
So? Any news?

**Comment by Parker11011** [comment] 2017-08-18 00:17
Somebody knows what microchip( or components) use the R4 cards ? Maybe I have the possibility to read it on my colleague, but I need to know the specifications about it .

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DiamondMinerITA** [comment] 2017-08-18 11:53
i've done an hd scan of a pretty close card and you can read the models.
@Parker11011

**Comment by DiamondMinerITA** [comment] 2017-08-20 11:16
Any news?

**Comment by N00byKing** [comment] 2017-08-22 10:14
I don't know if this helps or not, but i have this DSTT clone which ALSO has r4i-gold.hk as its Homepage, but the thing about it is that it's also compatible with the Ace3DS Updater that was posted here first. Before, it identified as some Spongebob Game (Sorry, but i forgot to take a Picture), and now it does as this thing:

![New Identity](https://user-images.githubusercontent.com/8339445/29560307-eb276360-8731-11e7-84fd-3ae4957ec1a8.jpeg)

After flashing it still works as expected.

Chip ID and Rev are the same as the Ace3DS (Suprise! /s), so:
ChipID: 00000FC2
HW Rev: 00000000

Pictures of the Card:
![Another r4i-gold.hk](https://user-images.githubusercontent.com/8339445/29560016-02abf5c4-8731-11e7-8fa7-d82ce8d9f9c0.jpeg)
![Another r4i-gold.hk](https://user-images.githubusercontent.com/8339445/29560015-02ab6190-8731-11e7-9940-debf88ebd4e5.jpeg)
![Another r4i-gold.hk](https://user-images.githubusercontent.com/8339445/29560018-02ace7fe-8731-11e7-95ea-9b083cf8f27d.jpeg)

**Comment by DiamondMinerITA** [comment] 2017-08-24 10:12
the dstt flash checker says that my r4 isn't a dstt :(
But wait, it has all the dstt files!
It even has a dstt.dat

**Comment by N00byKing** [comment] 2017-08-24 13:07
The Flasher is very specific, i have another DSTT Clone where it doesnt work. I took both apart, and they look the same.

Maybe i just suck at "spot the difference", maybe you can see it

![dsill](https://user-images.githubusercontent.com/8339445/29667727-cc9b3f0e-88dd-11e7-972f-effda8d0b83d.jpeg)
![dsill](https://user-images.githubusercontent.com/8339445/29667732-ce225d62-88dd-11e7-8138-0b11fc106e03.jpeg)
![dsill](https://user-images.githubusercontent.com/8339445/29667735-cef3c69a-88dd-11e7-9868-169cc5adc553.jpeg)

**Comment by dark-samus** [comment] 2017-08-24 16:52
they use different flashes. The flasher I posted has about 53 flashes that it detects, but I've seen at least 5 or 6 more flashes that aren't on it's list. Taking apart the updaters, I've noticed the flash commands are very very similar, so once we support DSTT, we should be able to also support these. The main problem is that there are just sooo many flash chips out there. there are around 60 that we know of, and some we can't find needed information about to support. It'll be a long road, but we can hopefully support everything. For now, waiting is your only option.

**Comment by DiamondMinerITA** [comment] 2017-08-24 20:19
@dark-samus at least can't be there like a Write only flasher?
Some of us have multiple old r4s and will be able to sacrifice one

**Comment by Valeri0p** [comment] 2017-09-11 12:11
Isn't this a duplicate of #56 ?

**Comment by dark-samus** [comment] 2017-09-11 14:37
technically, #56 is a duplicate of this :P but, yeah, this can probably be closed now.

**Closed by dark-samus** 2017-09-11 14:37 UTC

**Comment by cramirez77** [comment] 2018-04-01 20:29
Hello everyone. Just checking to see if anyone has figure out how to get the v1 of ACD3D to work with 11.6 firmware? Thanks
