### ISSUE TITLE
R4iTT 3DS NEW (http://www.r4itt.net/en_US_home.html)

### ISSUE THREAD

**Issue by JellyVGC** [kitling/flashcart_core#66] opened 2017-09-19 23:43 UTC
ChipID: 00000FC2
HW Revision: 2A2A2A2A

Link to Firmware and Kernal:
http://www.r4itt.net/en_US_gameklist1.html

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

![front](https://user-images.githubusercontent.com/32113505/30620307-5bb69870-9d59-11e7-8608-c229e25d1d79.jpg)
![front pcb](https://user-images.githubusercontent.com/32113505/30635358-05ff1a80-9da7-11e7-8eee-dae9637fe1cb.jpg)
![back pcb](https://user-images.githubusercontent.com/32113505/30635363-09a4437c-9da7-11e7-92d4-45ea6d875f66.jpg)
![capture](https://user-images.githubusercontent.com/32113505/30621089-fe4ad61a-9d5d-11e7-81c9-c0046aa7adea.PNG)
This is what it shows as the game when in the 3ds
![flashcart](https://user-images.githubusercontent.com/32113505/30634408-dade2358-9da3-11e7-9b14-367ebbbcc6d0.PNG)
In gm9
![gm9](https://user-images.githubusercontent.com/32113505/30635768-4bf42dc2-9da8-11e7-9fdc-8d91767d4b1e.PNG)
Load up Menu
![load up menu](https://user-images.githubusercontent.com/32113505/30635782-58740982-9da8-11e7-8789-0970ff0b9ce7.PNG)

</p></details> 

GM9 Untrimmed Dump: 
https://mega.nz/#!ecwX3CCR!blzbvaBPJw9MJD6m6PvYq675vxqsJbHHIpRBIKqYceE

**Comment by dark-samus** [comment] 2017-09-20 15:18
duplicate of #3

**Closed by dark-samus** 2017-09-20 15:18 UTC
