### ISSUE TITLE
3DS R4GOLD 2014 (www.R4igold.cc) 

### ISSUE THREAD

**Issue by NichyXD** [kitling/flashcart_core#30] opened 2017-08-24 21:55 UTC
Hi! These are the details:

**Game Header:**

> SpongeBob's 
> Atlantis Squarepantis
> THQ

![spong](https://user-images.githubusercontent.com/13277753/29690251-7f183d10-8926-11e7-83aa-3486f1c54bda.jpg)

**Flashcart skin:**

![skin](https://user-images.githubusercontent.com/13277753/29690279-a7ebd972-8926-11e7-9ff4-9f3badf9173b.jpg)

**Flashcart PCB:**

![flash1](https://user-images.githubusercontent.com/13277753/29690333-d92944d4-8926-11e7-971c-827f517c08f7.jpeg)

![noflash](https://user-images.githubusercontent.com/13277753/29690355-ee5a0fdc-8926-11e7-8f6b-ccea43cfe2e8.jpeg)

**Hardware information:**

> ChipID: 00000FC2
> HW Rev: 2A2A2A2A

![hwinfo](https://user-images.githubusercontent.com/13277753/29690429-3d582ae2-8927-11e7-9973-d9f0f31e8042.jpg)

**Kernel:**

http://www.r4igold.cc/pic/r4igold_3ds_v3.7.rar

**Upgrader:**

http://www.r4igold.cc/pic/Update_7.0_r4igold3ds_2.nds.rar

**Official website:**

http://www.r4igold.cc/3ds_main.asp

A little bird told me that is being worked :) It's true?

**Comment by Juanito9001** [comment] 2017-08-24 22:04
not yet... they're testing right now (this card had an issue, but i don`t know what happened... ,if its still open, do your question there) meanwhile... wait... because like i told you, the developers are testing and once they work, they gonna publish the version

**Comment by dark-samus** [comment] 2017-08-24 22:15
sorry, this is a duplicate of #3 so I'll be closing this one. Please post anything further in that thread. Thanks.

**Closed by dark-samus** 2017-08-24 22:15 UTC
